#!/bin/sh
# live-build configuration script
# see 'man lb config'
mirror=https://mirrors.tuna.tsinghua.edu.cn

lb config noauto \
--apt-http-proxy http://192.168.3.144:7890
--apt-recommends false \
--apt-secure false \
--apt-indices false \
--architectures amd64 \
--archive-areas 'main contrib non-free' \
--backports true \
--security true \
--updates true \
--source false \
--binary-filesystem ext4 \
--binary-images iso-hybrid \
--checksums sha256 \
--clean \
--debconf-frontend noninteractive \
--debian-installer live \
--debian-installer-distribution bullseye \
--debian-installer-gui true \
--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
--distribution bullseye \
--firmware-binary true \
--firmware-chroot true \
--initramfs live-boot \
--iso-publisher dlc \
--iso-volume dlc-3.0.0 \
--linux-packages "linux-image linux-headers" \
--bootappend-live "boot=live config splash" \
--memtest memtest86+ \
--win32-loader true \
--mirror-binary $mirror/debian/ \
--mirror-binary-security $mirror/debian-security/ \
--mirror-bootstrap $mirror/debian/ \
--mirror-chroot $mirror/debian/ \
--mirror-chroot-security $mirror/debian-security/ \
--mirror-debian-installer $mirror/debian/ \
--verbose true \
--zsync true

"${@}"
